// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeDeleteRoute, makeGetRoute, makePostRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as LngRoute from "@/app/[lng]/page.info";
import * as AdminDashboardRoute from "@/app/[lng]/(admin)/admin/page.info";
import * as AdminPhotosRoute from "@/app/[lng]/(admin)/admin/photos/page.info";
import * as AdminLoginRoute from "@/app/[lng]/(public)/admin/login/page.info";
import * as GalleryRoute from "@/app/[lng]/(public)/gallery/page.info";
import * as LngSentryExamplePageRoute from "@/app/[lng]/sentry-example-page/page.info";
import * as ApiAdminPhotosRoute from "@/app/api/admin/photos/route.info";
import * as ApiAdminPhotosIdRoute from "@/app/api/admin/photos/[id]/route.info";
import * as ApiAdminPhotosConfirmRoute from "@/app/api/admin/photos/confirm/route.info";
import * as ApiAdminPhotosCreatePresignedRoute from "@/app/api/admin/photos/create-presigned/route.info";
import * as ApiAuthNextauthRoute from "@/app/api/auth/[...nextauth]/route.info";
import * as ApiPhotosRoute from "@/app/api/photos/route.info";
import * as ApiSentryExampleApiRoute from "@/app/api/sentry-example-api/route.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Lng = makeRoute(
  "/[lng]",
  {
    ...defaultInfo,
    ...LngRoute.Route
  }
);
export const AdminDashboard = makeRoute(
  "/[lng]/(admin)/admin",
  {
    ...defaultInfo,
    ...AdminDashboardRoute.Route
  }
);
export const AdminPhotos = makeRoute(
  "/[lng]/(admin)/admin/photos",
  {
    ...defaultInfo,
    ...AdminPhotosRoute.Route
  }
);
export const AdminLogin = makeRoute(
  "/[lng]/(public)/admin/login",
  {
    ...defaultInfo,
    ...AdminLoginRoute.Route
  }
);
export const Gallery = makeRoute(
  "/[lng]/(public)/gallery",
  {
    ...defaultInfo,
    ...GalleryRoute.Route
  }
);
export const LngSentryExamplePage = makeRoute(
  "/[lng]/sentry-example-page",
  {
    ...defaultInfo,
    ...LngSentryExamplePageRoute.Route
  }
);
export const ApiAuthNextauth = makeRoute(
  "/api/auth/[...nextauth]",
  {
    ...defaultInfo,
    ...ApiAuthNextauthRoute.Route
  }
);

export const getApiAdminPhotos = makeGetRoute(
  "/api/admin/photos",
  {
    ...defaultInfo,
    ...ApiAdminPhotosRoute.Route
  },
  ApiAdminPhotosRoute.GET
);
export const deleteApiAdminPhotosId = makeDeleteRoute(
  "/api/admin/photos/[id]",
  {
    ...defaultInfo,
    ...ApiAdminPhotosIdRoute.Route
  },
  
);
export const postApiAdminPhotosConfirm = makePostRoute(
  "/api/admin/photos/confirm",
  {
    ...defaultInfo,
    ...ApiAdminPhotosConfirmRoute.Route
  },
  ApiAdminPhotosConfirmRoute.POST
);
export const postApiAdminPhotosCreatePresigned = makePostRoute(
  "/api/admin/photos/create-presigned",
  {
    ...defaultInfo,
    ...ApiAdminPhotosCreatePresignedRoute.Route
  },
  ApiAdminPhotosCreatePresignedRoute.POST
);
export const getApiPhotos = makeGetRoute(
  "/api/photos",
  {
    ...defaultInfo,
    ...ApiPhotosRoute.Route
  },
  ApiPhotosRoute.GET
);
export const getApiSentryExampleApi = makeGetRoute(
  "/api/sentry-example-api",
  {
    ...defaultInfo,
    ...ApiSentryExampleApiRoute.Route
  },
  ApiSentryExampleApiRoute.GET
);
