// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as LngRoute from "@/app/[lng]/page.info";
import * as AdminDashboardRoute from "@/app/[lng]/(admin)/admin/page.info";
import * as AdminPhotosRoute from "@/app/[lng]/(admin)/admin/photos/page.info";
import * as AdminLoginRoute from "@/app/[lng]/(public)/admin/login/page.info";
import * as GalleryRoute from "@/app/[lng]/(public)/gallery/page.info";
import * as ApiAuthNextauthRoute from "@/app/api/auth/[...nextauth]/route.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Lng = makeRoute(
  "/[lng]",
  {
    ...defaultInfo,
    ...LngRoute.Route
  }
);
export const AdminDashboard = makeRoute(
  "/[lng]/(admin)/admin",
  {
    ...defaultInfo,
    ...AdminDashboardRoute.Route
  }
);
export const AdminPhotos = makeRoute(
  "/[lng]/(admin)/admin/photos",
  {
    ...defaultInfo,
    ...AdminPhotosRoute.Route
  }
);
export const AdminLogin = makeRoute(
  "/[lng]/(public)/admin/login",
  {
    ...defaultInfo,
    ...AdminLoginRoute.Route
  }
);
export const Gallery = makeRoute(
  "/[lng]/(public)/gallery",
  {
    ...defaultInfo,
    ...GalleryRoute.Route
  }
);
export const ApiAuthNextauth = makeRoute(
  "/api/auth/[...nextauth]",
  {
    ...defaultInfo,
    ...ApiAuthNextauthRoute.Route
  }
);

